name: Predlog / pitanje tima
description: Predlog, pitanje o specifikaciji ili prijava problema u projektu
title: "[OIB] "
labels: ["triage"]
body:
  - type: textarea
    id: context
    attributes:
      label: Kontekst
      description: Opišite celinu, zadatak i šta pokušavate da postignete.
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Pitanje ili predlog
    validations:
      required: true
  - type: textarea
    id: security
    attributes:
      label: Bezbednosni uticaj
      description: Koji asset, trust granica ili bezbednosni zahtev je pogođen?
